### ISSUE TITLE
curl: (26) Failed to open/read local data from file/application

### ISSUE THREAD

**Issue by DasCanard** [sinshutu/upload-to-discord#7]
YML File
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew 1.8.9-Forge:build
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Nightly Build
        # A file, directory or wildcard pattern that describes what to upload
        path: 1.8.9-Forge/build/libs/*.jar

    - uses: actions/checkout@master
    - name: Send file LiquidBounce Jar to discord channel
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: ./1.8.9-Forge/build/libs/*.jar`

**Comment by sinshutu** [comment]
@DasCanard 

I looked this.  => https://github.com/DasCanard/LiquidBounce/runs/639246866?check_suite_focus=true

It looks like the cause is that actions/checkout is running before uploading the file.


I verified the above and it works, so I'll create a pull request.
verified: https://github.com/sinshutu/LiquidBounce/runs/640958802?check_suite_focus=true
PR: https://github.com/DasCanard/LiquidBounce/pull/1

**Comment by DasCanard** [comment]
Yeah thanks!
